services:
  naver-collector:
    build: .
    container_name: naver-collector-vm
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
    env_file:
      - .env
    volumes:
      # 결과를 로컬에서 확인할 수 있도록 마운트
      - ./collectors/results:/app/collectors/results
      # 로그 확인용
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    # 무료티어 VM 최적화 설정
    deploy:
      resources:
        limits:
          memory: 800M  # 1GB 중 800MB만 사용 (OS용 200MB 확보)
        reservations:
          memory: 400M
    # VM 최적화: 순차 처리 + 요청 간격
    command: >
      bash -c "cd collectors && 
      python3 parallel_batch_collect_gangnam.py 1"
    restart: unless-stopped