version: '3.8'

services:
  # EC2 동일 환경 테스트 컨테이너
  ec2-test:
    build:
      context: .
      dockerfile: Dockerfile.ec2-test
    container_name: naver-collector-ec2-test
    volumes:
      # 토큰 캐시 파일 (호스트와 동기화)
      - ./collectors/cached_token.json:/home/ubuntu/naver_land/collectors/cached_token.json
      # 수집 결과 (호스트와 동기화)  
      - ./collectors/results:/home/ubuntu/naver_land/collectors/results
      # 로그 파일 (호스트와 동기화)
      - ./logs:/home/ubuntu/naver_land/logs
      # .env 파일 (호스트와 동기화)
      - ./.env:/home/ubuntu/naver_land/.env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
    # 메모리 제한 (EC2 t2.micro 환경 시뮬레이션)
    mem_limit: 1g
    # CPU 제한 (EC2 t2.micro 환경 시뮬레이션)  
    cpus: '1.0'
    # 대화형 모드
    stdin_open: true
    tty: true
    # 자동 재시작 비활성화 (테스트용)
    restart: "no"

  # 성능 테스트용 (메모리 제한 없음)
  performance-test:
    build:
      context: .
      dockerfile: Dockerfile.ec2-test
    container_name: naver-collector-performance-test
    volumes:
      - ./collectors/cached_token.json:/home/ubuntu/naver_land/collectors/cached_token.json
      - ./collectors/results:/home/ubuntu/naver_land/collectors/results
      - ./logs:/home/ubuntu/naver_land/logs
      - ./.env:/home/ubuntu/naver_land/.env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
    # 메모리 제한 없음 (성능 비교용)
    stdin_open: true
    tty: true
    restart: "no"

  # t3.small 환경 시뮬레이션
  t3-small-test:
    build:
      context: .
      dockerfile: Dockerfile.ec2-test
    container_name: naver-collector-t3-small-test
    volumes:
      - ./collectors/cached_token.json:/home/ubuntu/naver_land/collectors/cached_token.json
      - ./collectors/results:/home/ubuntu/naver_land/collectors/results
      - ./logs:/home/ubuntu/naver_land/logs
      - ./.env:/home/ubuntu/naver_land/.env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
    # t3.small 환경 시뮬레이션 (2GB RAM, 2 vCPU)
    mem_limit: 2g
    cpus: '2.0'
    stdin_open: true
    tty: true
    restart: "no"