version: '3.8'

services:
  naver-collector:
    build: .
    container_name: naver-collector
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
    env_file:
      - .env
    volumes:
      # 결과를 로컬에서 확인할 수 있도록 마운트
      - ./collectors/results:/app/collectors/results
      # 로그 확인용
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    # 테스트용 명령 (단일 동만 수집)
    command: >
      bash -c "cd collectors && 
      python3 fixed_naver_collector.py 1168011300 true 1"